name: Build
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    if: github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    name: Build
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew build --stacktrace
